version: 2.1

orbs:
  goreleaser: ory/goreleaser@0.1.1
  slack: circleci/slack@3.4.2

workflows:
  default:
    jobs:
      - goreleaser/test
      - goreleaser/release:
          requires:
            - goreleaser/test
          filters:
            branches:
              ignore: /.*/

      - goreleaser/newsletter-draft:
          requires:
            - goreleaser/release
      - slack/approval-notification:
          message: Pending approval
          channel: release-automation
          requires:
            - goreleaser/newsletter-draft
      - newsletter-approval:
          type: approval
          requires:
            - goreleaser/newsletter-draft
      - goreleaser/newsletter-send:
          requires:
            - newsletter-approval
