version: 2.1

orbs:
  goreleaser: ory/goreleaser@0.1.1

workflows:
  default:
    jobs:
      - goreleaser/test:
      - goreleaser/release:
          requires:
            - goreleaser/test
          filters:
            branches:
              ignore: /.*/

      - goreleaser/newsletter-draft:
          requires:
            - goreleaser/release
      - newsletter-approval:
          type: approval
          requires:
            - goreleaser/newsletter-draft
      - goreleaser/newsletter-send:
          requires:
            - newsletter-approval
