version: 2.1

orbs:
  goreleaser: ory/goreleaser@0.1.2
  slack: circleci/slack@3.4.2

workflows:
  default:
    jobs:
      -
        goreleaser/test:
          filters:
            tags:
              only: /.*/
      -
        goreleaser/release:
          requires:
            - goreleaser/test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

      -
        goreleaser/newsletter-draft:
          requires:
            - goreleaser/release
          filters:
            tags:
              only: /.*/
      -
        slack/approval-notification:
          message: Pending approval
          channel: release-automation
          requires:
            - goreleaser/newsletter-draft
          filters:
            tags:
              only: /.*/
      -
        newsletter-approval:
          type: approval
          requires:
            - goreleaser/newsletter-draft
          filters:
            tags:
              only: /.*/
      -
        goreleaser/newsletter-send:
          requires:
            - newsletter-approval
          filters:
            tags:
              only: /.*/
